application: pcaphar
version: 1
runtime: python
api_version: 1

handlers:
- url: /harviewer
  static_dir: harviewer

- url: /examples
  static_dir: examples

- url: /images
  static_dir: images

- url: /.*
  script: pcaphar.py
