application: pcapperf2
version: 2
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

libraries:                                                                       
- name: jinja2                                                                   
  version: latest                                                                

handlers:
- url: /favicon.ico
  expiration: '7d'
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /harviewer/examples
  expiration: '7d'
  mime_type: 'text/plain'
  static_dir: harviewer/examples

- url: /harviewer
  expiration: '7d'
  static_dir: harviewer

- url: /examples
  expiration: '7d'
  static_dir: examples

- url: /images
  expiration: '7d'
  static_dir: images

- url: /fastbutton
  script: testing.app

- url: /.*
  script: pcaphar.app
